title: 5 Operating Systems
author: Designer Studios
email: adamabdallah2011@outlook.com


# social links
github_username: designer-studios

show_excerpts: true # set to false to remove excerpts on the homepage
